name: GitHub Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
