on:
  push:
    branches:
      - master
      - 0.28.x
      - 0.29.x
      - 'test-ci/**'
  pull_request:

name: Release

jobs:
  release:
    name: Release - dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v4
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: run cargo
        run: contrib/release.sh
